version: 1.0
publish: app
services:
  app:
    command: npm run build && npm run start
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 80
        public: 80